apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-kuber
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: kuber-app
          image: usercrud:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: usercrudsecret
                  key: dbhost
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: usercrudsecret
                  key: dbport
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: usercrudsecret
                  key: dbname
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: usercrudsecret
                  key: dbusername
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: usercrudsecret
                  key: dbpassword