apiVersion: v1
kind: Secret
metadata:
  name: usercrudsecret
type: Opaque
data:
  dbhost: bXlzcWwudXNlcmNydWQuc3ZjLmNsdXN0ZXIubG9jYWw=
  dbport: MzMwNg==
  dbname: bXlfZGF0YWJhc2U=
  dbusername: cm9vdA==
  dbpassword: cm9vdA==